### ISSUE TITLE
2021 missing analytics - before latest fix

### ISSUE THREAD

**Issue by kachaj7** [kaltura/dwh#31]
Hi,

https://github.com/kaltura/dwh/commit/c642531c6bd8c7e9af35c489a70ea48b949bafd0
https://github.com/kaltura/dwh/commit/b0b0288063c06216ef0a2fecb68cffcfe6950c36

I made this fix, but still I have missing 4 days of statistics from beginning of the year.
How to regenerate this days? Need I change the status value of the kalturadw_ds.cycles table?

**Comment by kaltura-hooks** [comment]
Hi @kachaj7,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by kachaj7** [comment]
Thank you for fast answer. There is new issue on forum: https://forum.kaltura.org/t/year-2021-analytics-problem/10801
